name: Lint PR Titles
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
jobs:
  pr-lint:
    name: Lint PR Titles
    runs-on: ubuntu-latest
    steps:
      - uses: Weburz/pr-lint-action@v0.0.1