name: Release
on:
  workflow_dispatch:
#  push:
#    branches:
#      - main
jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release-tag: ${{ steps.release-please.outputs.tag_name }}
      version: ${{ steps.release-please.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          release-type: 'rust'
          target-branch: ${{ github.ref_name }}

  build:
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    needs: release
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: Build project
        run: cargo build --release
        env:
          CARGO_PKG_VERSION: ${{ needs.release.outputs.version }}

      - name: Upload artifacts
        uses: AButler/upload-release-assets@v3.0
        with:
          files: "target/release/bongo?(.exe)"
          release-tag: ${{ needs.release.outputs.release-tag }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}